### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by multimeric** [multimeric/RustLangRetweet#5]
This can just be a basic build/test/link for PRs and such. It doesn't need to do deployment since that poses a security risk.

**Comment by DipayanP007** [comment]
Hi @multimeric can I work on this?

**Comment by multimeric** [comment]
Sure, if you would like

**Comment by DipayanP007** [comment]
Can you just help me what commands to run. Are they
* `cargo build`
* `cargo test`
???

**Comment by multimeric** [comment]
I would look to see what existing github actions there are. For the moment just `build` and some kind of linting like `rustfmt` need to be run. The tests are a bit tricky because they require API tokens which I will have to set up.

**Comment by DipayanP007** [comment]
Hey @multimeric Sorry I became a bit busy. Regarding the source code it shows this error
![Screenshot from 2022-01-24 23-24-32](https://user-images.githubusercontent.com/86959038/150837771-d3b776d3-2df0-4ae9-825e-0bc2d6722f4c.png)

**Comment by multimeric** [comment]
The top error is because you haven't got a new enough Rust version. You need 1.58+ as I'm using a new feature for format strings.

**Comment by DipayanP007** [comment]
Hey @multimeric I have created a PR for the issue. kindly review it

**Comment by DipayanP007** [comment]
Hey @multimeric I mistakenly closed the PR and so I raised another PR with the required changes. Kindly review it
